---
# Install
- name: Ensure Homebrew is installed and properly configured
  include_tasks: install.yml

# Taps
- name: Ensure configured taps are tapped.
  include_tasks: tap.yml
  loop_control:
    loop_var: tap
  with_items: "{{ homebrew_taps }}"
  tags:
    - brew_casks
    - brew_packages

# Cask.
- name: Install configured cask applications.
  loop_control:
    loop_var: cask
  include_tasks: cask.yml
  with_items: "{{ homebrew_cask_apps }}"
  tags: [ 'brew_casks']

- name: "Refresh sudo access to prevent password prompt for cask that requires admin rights"
  command: "echo none"
  become: yes
  tags: [ 'brew_casks']

- name: Install configured cask applications that requires admin rights.
  loop_control:
    loop_var: cask
  include_tasks: cask.yml
  with_items: "{{ homebrew_cask_apps_with_admin_rights }}"
  tags: [ 'brew_casks']

- name: Ensure blacklisted cask applications are not installed.
  homebrew_cask:
    name: "{{ item }}"
    state: absent
  with_items: "{{ homebrew_cask_uninstalled_apps }}"
  tags: [ 'brew_casks']

# Brew.
- name: Ensure configured homebrew packages are installed.
  include_tasks: package.yml
  loop_control:
    loop_var: package
  with_items: "{{ homebrew_installed_packages }}"
  tags: [ 'brew_packages']

- name: Ensure configured homebrew packages that needs admin rights are installed.
  include_tasks: package.yml
  loop_control:
    loop_var: package
  with_items: "{{ homebrew_installed_packages_with_admin_rights }}"
  tags: [ 'brew_packages']

- name: Ensure blacklisted homebrew packages are not installed.
  homebrew:
    name: "{{ item }}"
    state: absent
  with_items: "{{ homebrew_uninstalled_packages }}"
  tags: [ 'brew_packages']

- name: Upgrade all homebrew packages (if configured).
  homebrew:
    update_homebrew: yes
    upgrade_all: yes
  when: homebrew_upgrade_all_packages
  tags: [ 'brew_packages']

- name: Check for Brewfile.
  stat:
    path: "{{ homebrew_brewfile_dir }}/Brewfile"
  register: homebrew_brewfile

- name: Install from Brewfile.
  command: "brew bundle chdir={{ homebrew_brewfile_dir }}"
  when: homebrew_brewfile.stat.exists and homebrew_use_brewfile

#Services
- name: Start brew services
  command: "/usr/local/bin/brew services start {{ item }}"
  with_items: "{{ homebrew_services }}"
  tags: [ 'brew_services' ]
